[tox]
envlist = py310, py311, py312, py313, py314, flake8, docs

[gh-actions]
python =
    3.14: flake8, docs, py314
    3.13: py313
    3.12: py312
    3.11: py311
    3.10: py310

[testenv:docs]
allowlist_externals=sh
deps =
    sphinx
    sphinx_rtd_theme
    rstcheck
commands =
    sh -c 'rm -f docs/source/zpywallet*rst docs/source/modules.rst'
    sphinx-apidoc -o docs/source zpywallet
    python docs/source/patch_modules.py
    sphinx-build -W -b html docs/source docs/build
    rstcheck README.rst

[testenv:flake8]
select = C,E,F,W,B,B950
extend-ignore = E203, E501, E704
deps = flake8
commands = flake8 --select=C,E,F,W,B,B950 --extend-ignore=W503,E203,E741,F401,E201 \
    --exclude=zpywallet/generated --max-line-length=120 zpywallet

[testenv]
deps = pytest
        pytest-benchmark
        coverage
        -r requirements.txt
setenv =
    PYTHONPATH = {toxinidir}

commands = coverage run -m pytest tests
    coverage report
    coverage xml

[coverage:run]
relative_files = True
source = zpywallet/
branch = True
